-- UPSKILL_BD_TURMA2_12.ANTIGUIDADE definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."ANTIGUIDADE" 
   (	"ID" NUMBER(*,0), 
	"DE" NUMBER, 
	"ATE" NUMBER, 
	"PCT" NUMBER, 
	 CONSTRAINT "CK_ANTIGUIDADE_PERIODO" CHECK (de < ate) ENABLE, 
	 CONSTRAINT "PK_ANTIGUIDADE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.ATIVIDADE definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."ATIVIDADE" 
   (	"ID" NUMBER(*,0), 
	"NOME" VARCHAR2(50), 
	 CONSTRAINT "PK_ATIVIDADE" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.FORMULAFCM definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."FORMULAFCM" 
   (	"ID" NUMBER(*,0), 
	"FORMULA" VARCHAR2(1000), 
	 CONSTRAINT "PK_FORMULAFCM" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.FORMULAFCT definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."FORMULAFCT" 
   (	"ID" NUMBER(*,0), 
	"FORMULA" VARCHAR2(1000), 
	 CONSTRAINT "PK_FORMULAFCT" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.FUNCIONARIO definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."FUNCIONARIO" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(255), 
	"ID_FILIAL" NUMBER, 
	"SUPERVISOR" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.GENERO definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."GENERO" 
   (	"GENERO" VARCHAR2(1), 
	 CONSTRAINT "CK_GENERO_GENERO" CHECK (upper(genero) in ('F', 'M')) ENABLE, 
	 CONSTRAINT "PK_GENERO" PRIMARY KEY ("GENERO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.TIPOATLETA definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."TIPOATLETA" 
   (	"TIPO" NUMBER(*,0), 
	"NOME" VARCHAR2(20), 
	 CONSTRAINT "PK_TIPOATLETA" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.TIPO_FILIAL definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."TIPO_FILIAL" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(255), 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.ATLETA definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."ATLETA" 
   (	"ID" NUMBER(*,0), 
	"NOME" VARCHAR2(50), 
	"NIC" VARCHAR2(15) NOT NULL ENABLE, 
	"GENERO" VARCHAR2(1), 
	"DATA_NASCIMENTO" DATE, 
	"TIPO_ATLETA" NUMBER(*,0) NOT NULL ENABLE, 
	 CONSTRAINT "CK_ATLETA_DATA" CHECK (data_nascimento >= to_date('1940-01-01', 'yyyy-mm-dd')) ENABLE, 
	 CONSTRAINT "PK_ATLETA" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "UK_ATLETA_NIC" UNIQUE ("NIC")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ATLETA_TIPOATLETA" FOREIGN KEY ("TIPO_ATLETA")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."TIPOATLETA" ("TIPO") ENABLE, 
	 CONSTRAINT "FK_ATLETA_GENERO" FOREIGN KEY ("GENERO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."GENERO" ("GENERO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.COMPETICAO definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."COMPETICAO" 
   (	"ID" NUMBER(*,0), 
	"DATA" DATE, 
	"NOME" VARCHAR2(50), 
	"ID_ATIVIDADE" NUMBER(*,0), 
	 CONSTRAINT "PK_COMPETICAO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_COMPETICAO_ATIVIDADE" FOREIGN KEY ("ID_ATIVIDADE")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATIVIDADE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.FCM definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."FCM" 
   (	"ID_FORMULA" NUMBER(*,0), 
	"GENERO" VARCHAR2(1), 
	"ID_ATIVIDADE" NUMBER(*,0), 
	 CONSTRAINT "PK_FCM" PRIMARY KEY ("ID_FORMULA", "GENERO", "ID_ATIVIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_FCM_GENERO" FOREIGN KEY ("GENERO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."GENERO" ("GENERO") ENABLE, 
	 CONSTRAINT "FK_FCM_ATIVIDADE" FOREIGN KEY ("ID_ATIVIDADE")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATIVIDADE" ("ID") ENABLE, 
	 CONSTRAINT "FK_FCM_FORMULA" FOREIGN KEY ("ID_FORMULA")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."FORMULAFCM" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.FCT definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."FCT" 
   (	"ID_FORMULA" NUMBER(*,0), 
	 CONSTRAINT "PK_FCT" PRIMARY KEY ("ID_FORMULA")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_FCT_FORMULA" FOREIGN KEY ("ID_FORMULA")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."FORMULAFCT" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.FILIAL definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."FILIAL" 
   (	"ID" NUMBER, 
	"NOME" VARCHAR2(255), 
	"TIPO_FILIAL" NUMBER, 
	"MORADA" VARCHAR2(255), 
	"ID_RESPONSAVEL" NUMBER, 
	 PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_FILIAL_TIPOFILIAL" FOREIGN KEY ("TIPO_FILIAL")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."TIPO_FILIAL" ("ID") ENABLE, 
	 CONSTRAINT "FK_ID_RESPONSAVEL_FUNCIONARIO" FOREIGN KEY ("ID_RESPONSAVEL")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."FUNCIONARIO" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.PAGAMENTO definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."PAGAMENTO" 
   (	"ID" NUMBER(*,0), 
	"DATA" DATE, 
	"VALOR" NUMBER, 
	"ID_ATLETA" NUMBER(*,0), 
	 CONSTRAINT "CK_PAGAMENTO_VALOR" CHECK (valor > 0) ENABLE, 
	 CONSTRAINT "PK_PAGAMENTO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PAGAMENTO_ATLETA" FOREIGN KEY ("ID")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATLETA" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.PARTICIPA definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."PARTICIPA" 
   (	"ID_ATLETA" NUMBER(*,0), 
	"ID_COMPETICAO" NUMBER(*,0), 
	 CONSTRAINT "PK_PARTICIPA" PRIMARY KEY ("ID_ATLETA", "ID_COMPETICAO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PARTICIPA_ATLETA" FOREIGN KEY ("ID_ATLETA")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATLETA" ("ID") ENABLE, 
	 CONSTRAINT "FK_PARTICIPA_COMPETICAO" FOREIGN KEY ("ID_COMPETICAO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."COMPETICAO" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.PREMIO definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."PREMIO" 
   (	"ID" NUMBER(*,0), 
	"ID_ATLETA" NUMBER(*,0), 
	"ID_COMPETICAO" NUMBER(*,0), 
	"VALOR" NUMBER, 
	 CONSTRAINT "CK_PREMIO_VALOR" CHECK (valor > 0) ENABLE, 
	 CONSTRAINT "PK_PREMIO" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PREMIO_PARTICIPA" FOREIGN KEY ("ID_ATLETA", "ID_COMPETICAO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."PARTICIPA" ("ID_ATLETA", "ID_COMPETICAO") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.PROFISSIONAL definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."PROFISSIONAL" 
   (	"ID" NUMBER(*,0), 
	"PCT_FIXA" NUMBER(5,2), 
	 CONSTRAINT "PK_PROFISSIONAL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_PROFISSIONAL_ATLETA" FOREIGN KEY ("ID")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATLETA" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.SEMIPROFISSIONAL definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."SEMIPROFISSIONAL" 
   (	"ID" NUMBER(*,0), 
	"DATA_FILIACAO" DATE, 
	 CONSTRAINT "PK_SEMIPROFISSIONAL" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_SEMIPROFISSIONAL_ATLETA" FOREIGN KEY ("ID")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATLETA" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.TIPOAMADOR definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."TIPOAMADOR" 
   (	"TIPO" NUMBER(*,0), 
	"PCT_VARIAVEL" NUMBER(5,2), 
	 CONSTRAINT "PK_TIPOAMADOR" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TIPOAMADOR_TIPOATLETA" FOREIGN KEY ("TIPO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."TIPOATLETA" ("TIPO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.TIPOPROFISSIONAL definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."TIPOPROFISSIONAL" 
   (	"TIPO" NUMBER(*,0), 
	"PCT_VARIAVEL" NUMBER(5,2), 
	 CONSTRAINT "PK_TIPOPROFISSIONAL" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TIPOPROFISSIONAL" FOREIGN KEY ("TIPO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."TIPOATLETA" ("TIPO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.TIPOSEMIPROFISSIONAL definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."TIPOSEMIPROFISSIONAL" 
   (	"TIPO" NUMBER(*,0), 
	"PCT_FIXA" NUMBER(5,2), 
	 CONSTRAINT "PK_TIPOSEMIPROFISSIONAL" PRIMARY KEY ("TIPO")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_TIPOSEMIPROFISSIONAL" FOREIGN KEY ("TIPO")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."TIPOATLETA" ("TIPO") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.AMADOR definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."AMADOR" 
   (	"ID" NUMBER(*,0), 
	"DATA_FILIACAO" DATE, 
	 CONSTRAINT "PK_AMADOR" PRIMARY KEY ("ID")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_AMADOR_ATLETA" FOREIGN KEY ("ID")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATLETA" ("ID") ENABLE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;


-- UPSKILL_BD_TURMA2_12.ATIVIDADEATLETA definition

CREATE TABLE "UPSKILL_BD_TURMA2_12"."ATIVIDADEATLETA" 
   (	"ID_ATLETA" NUMBER(*,0), 
	"ID_ATIVIDADE" NUMBER(*,0), 
	 CONSTRAINT "PK_ATIVIDADEATLETA" PRIMARY KEY ("ID_ATLETA", "ID_ATIVIDADE")
  USING INDEX PCTFREE 10 INITRANS 2 MAXTRANS 255 COMPUTE STATISTICS 
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS"  ENABLE, 
	 CONSTRAINT "FK_ATIVIDADEATLETA_ATLETA" FOREIGN KEY ("ID_ATLETA")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATLETA" ("ID") ENABLE, 
	 CONSTRAINT "FK_ATIVIDADEATLETA_ATIVIDADE" FOREIGN KEY ("ID_ATIVIDADE")
	  REFERENCES "UPSKILL_BD_TURMA2_12"."ATIVIDADE" ("ID") ENABLE
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 
 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1
  BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
